
### api test 
GET http://localhost:8000/api/v1/user/

### POST user
POST http://localhost:8000/api/v1/user/
Content-Type: application/json

{
    "firstName":"Anmol",
    "lastName":"bhat",
    "email":"asd@asdasd",
    "password":"Anmol"
}


### POST new user
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    
    "email":"asd@asdasd",
    "password":"Anmol"
}
